import React, { useState } from "react";
import "../style/interview.scss";

const report = {
  matchScore: 70,

  technicalQuestions: [
    {
      question:
        "Given your experience with React.js, can you explain the concept of hooks and describe a scenario where you would use useMemo or useCallback for performance optimization?",
      intention: "Generated by AI",
      answer: "Prepare a detailed answer",
    },
    {
      question:
        "How do you handle authentication and authorization in REST APIs?",
      intention: "Generated by AI",
      answer: "Prepare a detailed answer",
    },
  ],

  behavioralQuestions: [
    {
      question:
        "Tell me about a challenging technical problem you encountered.",
      intention: "Assess soft skills",
      answer: "Use STAR method",
    },
  ],

  preparationPlan: [
    {
      day: 1,
      tasks: ["Learn TypeScript fundamentals"],
    },
    {
      day: 2,
      tasks: ["Learn Docker basics"],
    },
  ],

  skillGaps: [
    { skill: "TypeScript" },
    { skill: "Docker" },
    { skill: "AWS" },
    { skill: "Production Deployment" },
  ],
};

const Interview = () => {
  const [activeTab, setActiveTab] = useState("technical");
  const [openQuestion, setOpenQuestion] = useState(null);

  const getData = () => {
    switch (activeTab) {
      case "technical":
        return report.technicalQuestions;

      case "behavioral":
        return report.behavioralQuestions;

      case "roadmap":
        return report.preparationPlan;

      default:
        return [];
    }
  };

  const currentData = getData();

  return (
    <main className="interview">
      <div className="dashboard">
        {/* SIDEBAR */}

        <aside className="sidebar">
          <h5>SECTIONS</h5>

          <button
            className={activeTab === "technical" ? "active" : ""}
            onClick={() => setActiveTab("technical")}
          >
            Technical Questions
          </button>

          <button
            className={activeTab === "behavioral" ? "active" : ""}
            onClick={() => setActiveTab("behavioral")}
          >
            Behavioral Questions
          </button>

          <button
            className={activeTab === "roadmap" ? "active" : ""}
            onClick={() => setActiveTab("roadmap")}
          >
            Road Map
          </button>

          <button className="download-btn">
            Download Resume
          </button>
        </aside>

        {/* MAIN CONTENT */}

        <section className="questions-panel">
          <div className="panel-header">
            <div className="left-header">
              <h2>
                {activeTab === "technical" &&
                  "Technical Questions"}

                {activeTab === "behavioral" &&
                  "Behavioral Questions"}

                {activeTab === "roadmap" &&
                  "Preparation Road Map"}
              </h2>

              <span>
                {currentData.length} Questions
              </span>
            </div>

            <p>
              0/{currentData.length} reviewed
            </p>
          </div>

          <div className="questions-list">

            {currentData.map((item, index) => (
              <div
                className="question-card"
                key={index}
              >
                <div
                  className="question-head"
                  onClick={() =>
                    setOpenQuestion(
                      openQuestion === index
                        ? null
                        : index
                    )
                  }
                >
                  <div className="question-info">

                    <input type="radio" />

                    <span className="q-badge">
                      Q{index + 1}
                    </span>

                    <p>
                      {item.question ||
                        item.tasks?.[0]}
                    </p>
                  </div>

                  <span className="expand-icon">
                    {openQuestion === index
                      ? "−"
                      : "+"}
                  </span>
                </div>

                {openQuestion === index &&
                  activeTab !== "roadmap" && (
                    <div className="question-body">
                      <h4>Intention</h4>

                      <p>
                        {item.intention}
                      </p>

                      <h4>Preparation Hint</h4>

                      <p>
                        {item.answer}
                      </p>
                    </div>
                  )}
              </div>
            ))}

          </div>
        </section>

        {/* RIGHT PANEL */}

        <aside className="stats-panel">
          <h5>MATCH SCORE</h5>

          <div className="score-circle">
            <div>
              <h2>
                {report.matchScore}
              </h2>

              <span>%</span>
            </div>
          </div>

          <p className="match-status">
            Moderate match — Work on gaps
          </p>

          <h5 className="skill-title">
            SKILL GAPS
          </h5>

          <div className="skills">
            {report.skillGaps.map(
              (skill, index) => (
                <span
                  key={index}
                  className="skill-tag"
                >
                  {skill.skill}
                </span>
              )
            )}
          </div>
        </aside>
      </div>
    </main>
  );
};

export default Interview;