import React, { useState } from "react";
import "../style/interview.scss";

const report = {
  matchScore: 70,

  technicalQuestions: [
    {
                "question": "Given your experience with React.js, can you explain the concept of hooks and describe a scenario where you would use `useMemo` or `useCallback` for performance optimization?",
                "intention": "Generated by AI",
                "answer": "Prepare a detailed answer"
            },
            {
                "question": "You've worked with Node.js and Express.js. How do you handle authentication and authorization in your REST APIs?",
                "intention": "Generated by AI",
                "answer": "Prepare a detailed answer"
            },
            {
                "question": "Describe your approach to designing a scalable database schema in MongoDB for an e-commerce application like your 'Super Mall Web Application'.",
                "intention": "Generated by AI",
                "answer": "Prepare a detailed answer"
            },
            {
                "question": "Can you explain the event loop in Node.js and how it allows Node.js to handle concurrent operations efficiently?",
                "intention": "Generated by AI",
                "answer": "Prepare a detailed answer"
            },
            {
                "question": "The job description mentions TypeScript as a requirement. What is your experience with TypeScript, and how would you go about integrating it into an existing JavaScript project?",
                "intention": "Generated by AI",
                "answer": "Prepare a detailed answer"
            },
            {
                "question": "You listed DSA in your competencies. Can you walk me through the solution for a common data structure problem, for example, finding the Kth smallest element in an array, and discuss its time and space complexity?",
                "intention": "Generated by AI",
                "answer": "Prepare a detailed answer"
            },
            {
                "question": "How do you ensure your web applications are secure, particularly against common vulnerabilities like XSS or CSRF?",
                "intention": "Generated by AI",
                "answer": "Prepare a detailed answer"
            },
  ],

  behavioralQuestions: [
     {
                "question": "Tell me about a challenging technical problem you encountered during the development of your 'Smart Inventory Management System' project. How did you approach it, and what was the outcome?",
                "intention": "Assess soft skills",
                "answer": "Use STAR method"
            },
            {
                "question": "The job requires collaboration with designers and backend engineers. Describe a situation where you had to effectively communicate a technical decision or compromise with team members who had different perspectives.",
                "intention": "Assess soft skills",
                "answer": "Use STAR method"
            },
            {
                "question": "How do you stay updated with the rapidly evolving web development landscape, and what new technology or framework are you currently excited about learning?",
                "intention": "Assess soft skills",
                "answer": "Use STAR method"
            },
            {
                "question": "Describe a time when you received feedback on your code or work that you initially disagreed with. How did you handle the situation and what did you learn?",
                "intention": "Assess soft skills",
                "answer": "Use STAR method"
            },
            {
                "question": "Given that you are still pursuing your B.Tech, how do you manage your time effectively between academics, projects, and learning new skills?",
                "intention": "Assess soft skills",
                "answer": "Use STAR method"
            },
  ],

  preparationPlan: [
    {
                "day": 1,
                "focus": "Interview Preparation",
                "tasks": [
                    "**Gain hands-on TypeScript Experience**: Work on personal projects using TypeScript, or refactor existing JavaScript projects to incorporate TypeScript to demonstrate proficiency."
                ],
                "_id": "6a32e4db948bba1768290808"
            },
            {
                "day": 2,
                "focus": "Interview Preparation",
                "tasks": [
                    "**Learn Docker**: Study Docker fundamentals, containerize existing MERN projects, and understand deployment using Docker containers."
                ],
                "_id": "6a32e4db948bba1768290809"
            },
            {
                "day": 3,
                "focus": "Interview Preparation",
                "tasks": [
                    "**Explore Broader Cloud Platforms**: Engage in tutorials and small projects leveraging services from AWS, Azure, or Google Cloud Platform (e.g., EC2, S3, Lambda, App Services) to expand cloud knowledge beyond Firebase."
                ],
                "_id": "6a32e4db948bba176829080a"
            },
            {
                "day": 4,
                "focus": "Interview Preparation",
                "tasks": [
                    "**Focus on System Design Fundamentals**: Begin learning about scalable architecture, microservices, and design patterns relevant to full-stack development to prepare for production-level challenges."
                ],
                "_id": "6a32e4db948bba176829080b"
            },
            {
                "day": 5,
                "focus": "Interview Preparation",
                "tasks": [
                    "**Deepen Advanced MERN Concepts**: Explore advanced topics in React (e.g., testing, performance tuning, state management libraries beyond `useState`/`useReducer`), Node.js security, and MongoDB indexing strategies."
                ],
                "_id": "6a32e4db948bba176829080c"
            },
            {
                "day": 6,
                "focus": "Interview Preparation",
                "tasks": [
                    "**Seek Internship/Part-time Opportunities**: Actively look for internships or part-time roles to bridge the professional experience gap and gain exposure to industry best practices and production environments."
                ],
                "_id": "6a32e4db948bba176829080d"
            },
            {
                "day": 7,
                "focus": "Interview Preparation",
                "tasks": [
                    "**Enhance Project Portfolio**: Develop more complex, full-stack applications that demonstrate a deeper understanding of scalable architecture, robust error handling, and security. Ensure clear READMEs and live demos are available."
                ],
                "_id": "6a32e4db948bba176829080e"
            }
  ],

  skillGaps: [
    { skill: "TypeScript" },
    { skill: "Docker" },
    { skill: "AWS" },
    { skill: "Production Deployment" },
  ],
};

const Interview = () => {
  const [activeTab, setActiveTab] = useState("technical");
  const [openQuestion, setOpenQuestion] = useState(null);

  const getData = () => {
    switch (activeTab) {
      case "technical":
        return report.technicalQuestions;

      case "behavioral":
        return report.behavioralQuestions;

      case "roadmap":
        return report.preparationPlan;

      default:
        return [];
    }
  };

  const currentData = getData();

  return (
    <main className="interview">
      <div className="dashboard">
        {/* SIDEBAR */}

        <aside className="sidebar">
          <h5>SECTIONS</h5>

          <button
            className={activeTab === "technical" ? "active" : ""}
            onClick={() => setActiveTab("technical")}
          >
            Technical Questions
          </button>

          <button
            className={activeTab === "behavioral" ? "active" : ""}
            onClick={() => setActiveTab("behavioral")}
          >
            Behavioral Questions
          </button>

          <button
            className={activeTab === "roadmap" ? "active" : ""}
            onClick={() => setActiveTab("roadmap")}
          >
            Road Map
          </button>

          <button className="download-btn">
            Download Resume
          </button>
        </aside>

        {/* MAIN CONTENT */}

        <section className="questions-panel">
          <div className="panel-header">
            <div className="left-header">
              <h2>
                {activeTab === "technical" &&
                  "Technical Questions"}

                {activeTab === "behavioral" &&
                  "Behavioral Questions"}

                {activeTab === "roadmap" &&
                  "Preparation Road Map"}
              </h2>

              <span>
                {currentData.length} Questions
              </span>
            </div>

            <p>
              0/{currentData.length} reviewed
            </p>
          </div>

          {/* <div className="questions-list">

            {currentData.map((item, index) => (
              <div
                className="question-card"
                key={index}
              >
                <div
                  className="question-head"
                  onClick={() =>
                    setOpenQuestion(
                      openQuestion === index
                        ? null
                        : index
                    )
                  }
                >
                  <div className="question-info">

                    <input type="radio" />

                    <span className="q-badge">
                      Q{index + 1}
                    </span>

                    <p>
                      {item.question ||
                        item.tasks?.[0]}
                    </p>
                  </div>

                  <span className="expand-icon">
                    {openQuestion === index
                      ? "−"
                      : "+"}
                  </span>
                </div>

                {openQuestion === index &&
                  activeTab !== "roadmap" && (
                    <div className="question-body">
                      <h4>Intention</h4>

                      <p>
                        {item.intention}
                      </p>

                      <h4>Preparation Hint</h4>

                      <p>
                        {item.answer}
                      </p>
                    </div>
                  )}
              </div>
            ))}

          </div> */}
          <div className="questions-list">

  {currentData.map((item, index) => (

    <div className="question-card" key={index}>

      <div
        className="question-head"
        onClick={() =>
          setOpenQuestion(
            openQuestion === index ? null : index
          )
        }
      >

        <div className="question-info">

          <input type="radio" />

          <span className="q-badge">
            {
              activeTab === "roadmap"
                ? `D${item.day}`
                : `Q${index + 1}`
            }
          </span>

          <div>

            {
              activeTab === "roadmap"
                ? (
                  <>
                    <h4 className="roadmap-focus">
                      Day {item.day}
                    </h4>

                    <p className="roadmap-title">
                      {item.focus}
                    </p>
                  </>
                )
                : (
                  <p>
                    {item.question}
                  </p>
                )
            }

          </div>

        </div>

        <span className="expand-icon">
      {
      openQuestion === index
        ? "⌃"
        : "⌄"
      }
</span>

      </div>


      {
        openQuestion === index && (

          <div className="question-body">

            {
              activeTab === "roadmap"
                ? (

                  <>
                    <h4>
                      Tasks
                    </h4>

                    <ul className="roadmap-tasks">

                      {
                        item.tasks.map((task, i) => (

                          <li key={i}>
                            {task}
                          </li>

                        ))
                      }

                    </ul>

                  </>
                )
                : (

                  <>
                    <h4>
                      Intention
                    </h4>

                    <p>
                      {item.intention}
                    </p>

                    <h4>
                      Preparation Hint
                    </h4>

                    <p>
                      {item.answer}
                    </p>

                  </>

                )
            }

          </div>

        )
      }

     </div>

    ))}

     </div>
        </section>

        {/* RIGHT PANEL */}

        <aside className="stats-panel">
          <h5>MATCH SCORE</h5>

          <div className="score-circle">
            <div>
              <h2>
                {report.matchScore}
              </h2>

              <span>%</span>
            </div>
          </div>

          <p className="match-status">
            Moderate match — Work on gaps
          </p>

          <h5 className="skill-title">
            SKILL GAPS
          </h5>

          <div className="skills">
            {report.skillGaps.map(
              (skill, index) => (
                <span
                  key={index}
                  className="skill-tag"
                >
                  {skill.skill}
                </span>
              )
            )}
          </div>
        </aside>
      </div>
    </main>
  );
};

export default Interview;